/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pina API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreatePantryItemDto,
  PantryItemResponseDto,
  ToggleStockDto,
} from "../../model";

import { customInstance } from "../../axios-instance";

/**
 * @summary Lista dispensa
 */
export const pantryControllerGetAll = (signal?: AbortSignal) => {
  return customInstance<PantryItemResponseDto[]>({
    url: `/pina/pantry`,
    method: "GET",
    signal,
  });
};

export const getPantryControllerGetAllQueryKey = () => {
  return [`/pina/pantry`] as const;
};

export const getPantryControllerGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof pantryControllerGetAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof pantryControllerGetAll>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPantryControllerGetAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof pantryControllerGetAll>>
  > = ({ signal }) => pantryControllerGetAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof pantryControllerGetAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PantryControllerGetAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof pantryControllerGetAll>>
>;
export type PantryControllerGetAllQueryError = unknown;

export function usePantryControllerGetAll<
  TData = Awaited<ReturnType<typeof pantryControllerGetAll>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pantryControllerGetAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pantryControllerGetAll>>,
          TError,
          Awaited<ReturnType<typeof pantryControllerGetAll>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePantryControllerGetAll<
  TData = Awaited<ReturnType<typeof pantryControllerGetAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pantryControllerGetAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pantryControllerGetAll>>,
          TError,
          Awaited<ReturnType<typeof pantryControllerGetAll>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePantryControllerGetAll<
  TData = Awaited<ReturnType<typeof pantryControllerGetAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pantryControllerGetAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Lista dispensa
 */

export function usePantryControllerGetAll<
  TData = Awaited<ReturnType<typeof pantryControllerGetAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pantryControllerGetAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPantryControllerGetAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Aggiungi articolo alla dispensa
 */
export const pantryControllerCreate = (
  createPantryItemDto: CreatePantryItemDto,
  signal?: AbortSignal,
) => {
  return customInstance<PantryItemResponseDto>({
    url: `/pina/pantry`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createPantryItemDto,
    signal,
  });
};

export const getPantryControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pantryControllerCreate>>,
    TError,
    { data: CreatePantryItemDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pantryControllerCreate>>,
  TError,
  { data: CreatePantryItemDto },
  TContext
> => {
  const mutationKey = ["pantryControllerCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pantryControllerCreate>>,
    { data: CreatePantryItemDto }
  > = (props) => {
    const { data } = props ?? {};

    return pantryControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PantryControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof pantryControllerCreate>>
>;
export type PantryControllerCreateMutationBody = CreatePantryItemDto;
export type PantryControllerCreateMutationError = unknown;

/**
 * @summary Aggiungi articolo alla dispensa
 */
export const usePantryControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pantryControllerCreate>>,
      TError,
      { data: CreatePantryItemDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pantryControllerCreate>>,
  TError,
  { data: CreatePantryItemDto },
  TContext
> => {
  const mutationOptions = getPantryControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Segna articolo come disponibile/non disponibile
 */
export const pantryControllerToggleStock = (
  itemId: string,
  toggleStockDto: ToggleStockDto,
) => {
  return customInstance<PantryItemResponseDto>({
    url: `/pina/pantry/${itemId}/toggle-stock`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: toggleStockDto,
  });
};

export const getPantryControllerToggleStockMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pantryControllerToggleStock>>,
    TError,
    { itemId: string; data: ToggleStockDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pantryControllerToggleStock>>,
  TError,
  { itemId: string; data: ToggleStockDto },
  TContext
> => {
  const mutationKey = ["pantryControllerToggleStock"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pantryControllerToggleStock>>,
    { itemId: string; data: ToggleStockDto }
  > = (props) => {
    const { itemId, data } = props ?? {};

    return pantryControllerToggleStock(itemId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PantryControllerToggleStockMutationResult = NonNullable<
  Awaited<ReturnType<typeof pantryControllerToggleStock>>
>;
export type PantryControllerToggleStockMutationBody = ToggleStockDto;
export type PantryControllerToggleStockMutationError = unknown;

/**
 * @summary Segna articolo come disponibile/non disponibile
 */
export const usePantryControllerToggleStock = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pantryControllerToggleStock>>,
      TError,
      { itemId: string; data: ToggleStockDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pantryControllerToggleStock>>,
  TError,
  { itemId: string; data: ToggleStockDto },
  TContext
> => {
  const mutationOptions =
    getPantryControllerToggleStockMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Rimuovi articolo dalla dispensa
 */
export const pantryControllerRemove = (itemId: string) => {
  return customInstance<void>({
    url: `/pina/pantry/${itemId}`,
    method: "DELETE",
  });
};

export const getPantryControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pantryControllerRemove>>,
    TError,
    { itemId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pantryControllerRemove>>,
  TError,
  { itemId: string },
  TContext
> => {
  const mutationKey = ["pantryControllerRemove"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pantryControllerRemove>>,
    { itemId: string }
  > = (props) => {
    const { itemId } = props ?? {};

    return pantryControllerRemove(itemId);
  };

  return { mutationFn, ...mutationOptions };
};

export type PantryControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof pantryControllerRemove>>
>;

export type PantryControllerRemoveMutationError = unknown;

/**
 * @summary Rimuovi articolo dalla dispensa
 */
export const usePantryControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pantryControllerRemove>>,
      TError,
      { itemId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pantryControllerRemove>>,
  TError,
  { itemId: string },
  TContext
> => {
  const mutationOptions = getPantryControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
