/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pina API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateRecipeDto,
  RecipesControllerRemove200,
  ResponseRecipeDto,
  UpdateRecipeDto,
} from "../../model";

import { customInstance } from "../../axios-instance";

/**
 * @summary Tutte le ricette della famiglia
 */
export const recipesControllerFindAll = (signal?: AbortSignal) => {
  return customInstance<ResponseRecipeDto[]>({
    url: `/recipes`,
    method: "GET",
    signal,
  });
};

export const getRecipesControllerFindAllQueryKey = () => {
  return [`/recipes`] as const;
};

export const getRecipesControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof recipesControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof recipesControllerFindAll>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getRecipesControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof recipesControllerFindAll>>
  > = ({ signal }) => recipesControllerFindAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof recipesControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RecipesControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof recipesControllerFindAll>>
>;
export type RecipesControllerFindAllQueryError = unknown;

export function useRecipesControllerFindAll<
  TData = Awaited<ReturnType<typeof recipesControllerFindAll>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recipesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof recipesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof recipesControllerFindAll>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRecipesControllerFindAll<
  TData = Awaited<ReturnType<typeof recipesControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recipesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof recipesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof recipesControllerFindAll>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRecipesControllerFindAll<
  TData = Awaited<ReturnType<typeof recipesControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recipesControllerFindAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Tutte le ricette della famiglia
 */

export function useRecipesControllerFindAll<
  TData = Awaited<ReturnType<typeof recipesControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recipesControllerFindAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getRecipesControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Crea ricetta
 */
export const recipesControllerCreate = (
  createRecipeDto: CreateRecipeDto,
  signal?: AbortSignal,
) => {
  return customInstance<ResponseRecipeDto>({
    url: `/recipes`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createRecipeDto,
    signal,
  });
};

export const getRecipesControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recipesControllerCreate>>,
    TError,
    { data: CreateRecipeDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recipesControllerCreate>>,
  TError,
  { data: CreateRecipeDto },
  TContext
> => {
  const mutationKey = ["recipesControllerCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recipesControllerCreate>>,
    { data: CreateRecipeDto }
  > = (props) => {
    const { data } = props ?? {};

    return recipesControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecipesControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof recipesControllerCreate>>
>;
export type RecipesControllerCreateMutationBody = CreateRecipeDto;
export type RecipesControllerCreateMutationError = unknown;

/**
 * @summary Crea ricetta
 */
export const useRecipesControllerCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recipesControllerCreate>>,
      TError,
      { data: CreateRecipeDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof recipesControllerCreate>>,
  TError,
  { data: CreateRecipeDto },
  TContext
> => {
  const mutationOptions = getRecipesControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Dettaglio ricetta
 */
export const recipesControllerFindOne = (
  recipeId: string,
  signal?: AbortSignal,
) => {
  return customInstance<ResponseRecipeDto>({
    url: `/recipes/${recipeId}`,
    method: "GET",
    signal,
  });
};

export const getRecipesControllerFindOneQueryKey = (recipeId?: string) => {
  return [`/recipes/${recipeId}`] as const;
};

export const getRecipesControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof recipesControllerFindOne>>,
  TError = unknown,
>(
  recipeId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recipesControllerFindOne>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getRecipesControllerFindOneQueryKey(recipeId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof recipesControllerFindOne>>
  > = ({ signal }) => recipesControllerFindOne(recipeId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!recipeId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof recipesControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RecipesControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof recipesControllerFindOne>>
>;
export type RecipesControllerFindOneQueryError = unknown;

export function useRecipesControllerFindOne<
  TData = Awaited<ReturnType<typeof recipesControllerFindOne>>,
  TError = unknown,
>(
  recipeId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recipesControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof recipesControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof recipesControllerFindOne>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRecipesControllerFindOne<
  TData = Awaited<ReturnType<typeof recipesControllerFindOne>>,
  TError = unknown,
>(
  recipeId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recipesControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof recipesControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof recipesControllerFindOne>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRecipesControllerFindOne<
  TData = Awaited<ReturnType<typeof recipesControllerFindOne>>,
  TError = unknown,
>(
  recipeId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recipesControllerFindOne>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Dettaglio ricetta
 */

export function useRecipesControllerFindOne<
  TData = Awaited<ReturnType<typeof recipesControllerFindOne>>,
  TError = unknown,
>(
  recipeId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recipesControllerFindOne>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getRecipesControllerFindOneQueryOptions(
    recipeId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Aggiorna ricetta
 */
export const recipesControllerUpdate = (
  recipeId: string,
  updateRecipeDto: UpdateRecipeDto,
) => {
  return customInstance<ResponseRecipeDto>({
    url: `/recipes/${recipeId}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateRecipeDto,
  });
};

export const getRecipesControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recipesControllerUpdate>>,
    TError,
    { recipeId: string; data: UpdateRecipeDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recipesControllerUpdate>>,
  TError,
  { recipeId: string; data: UpdateRecipeDto },
  TContext
> => {
  const mutationKey = ["recipesControllerUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recipesControllerUpdate>>,
    { recipeId: string; data: UpdateRecipeDto }
  > = (props) => {
    const { recipeId, data } = props ?? {};

    return recipesControllerUpdate(recipeId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecipesControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof recipesControllerUpdate>>
>;
export type RecipesControllerUpdateMutationBody = UpdateRecipeDto;
export type RecipesControllerUpdateMutationError = unknown;

/**
 * @summary Aggiorna ricetta
 */
export const useRecipesControllerUpdate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recipesControllerUpdate>>,
      TError,
      { recipeId: string; data: UpdateRecipeDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof recipesControllerUpdate>>,
  TError,
  { recipeId: string; data: UpdateRecipeDto },
  TContext
> => {
  const mutationOptions = getRecipesControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Elimina ricetta (soft delete)
 */
export const recipesControllerRemove = (recipeId: string) => {
  return customInstance<RecipesControllerRemove200>({
    url: `/recipes/${recipeId}`,
    method: "DELETE",
  });
};

export const getRecipesControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recipesControllerRemove>>,
    TError,
    { recipeId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recipesControllerRemove>>,
  TError,
  { recipeId: string },
  TContext
> => {
  const mutationKey = ["recipesControllerRemove"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recipesControllerRemove>>,
    { recipeId: string }
  > = (props) => {
    const { recipeId } = props ?? {};

    return recipesControllerRemove(recipeId);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecipesControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof recipesControllerRemove>>
>;

export type RecipesControllerRemoveMutationError = unknown;

/**
 * @summary Elimina ricetta (soft delete)
 */
export const useRecipesControllerRemove = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recipesControllerRemove>>,
      TError,
      { recipeId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof recipesControllerRemove>>,
  TError,
  { recipeId: string },
  TContext
> => {
  const mutationOptions = getRecipesControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
