/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pina API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AssignRecipeDto,
  PlanSlotResponseDto,
  PlannerControllerGetWeek200,
} from "../../model";

import { customInstance } from "../../axios-instance";

/**
 * @summary Piano settimana — tutti gli slot
 */
export const plannerControllerGetWeek = (
  weekKey: string,
  signal?: AbortSignal,
) => {
  return customInstance<PlannerControllerGetWeek200>({
    url: `/planner/${weekKey}`,
    method: "GET",
    signal,
  });
};

export const getPlannerControllerGetWeekQueryKey = (weekKey?: string) => {
  return [`/planner/${weekKey}`] as const;
};

export const getPlannerControllerGetWeekQueryOptions = <
  TData = Awaited<ReturnType<typeof plannerControllerGetWeek>>,
  TError = unknown,
>(
  weekKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof plannerControllerGetWeek>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPlannerControllerGetWeekQueryKey(weekKey);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof plannerControllerGetWeek>>
  > = ({ signal }) => plannerControllerGetWeek(weekKey, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!weekKey,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof plannerControllerGetWeek>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PlannerControllerGetWeekQueryResult = NonNullable<
  Awaited<ReturnType<typeof plannerControllerGetWeek>>
>;
export type PlannerControllerGetWeekQueryError = unknown;

export function usePlannerControllerGetWeek<
  TData = Awaited<ReturnType<typeof plannerControllerGetWeek>>,
  TError = unknown,
>(
  weekKey: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof plannerControllerGetWeek>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof plannerControllerGetWeek>>,
          TError,
          Awaited<ReturnType<typeof plannerControllerGetWeek>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePlannerControllerGetWeek<
  TData = Awaited<ReturnType<typeof plannerControllerGetWeek>>,
  TError = unknown,
>(
  weekKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof plannerControllerGetWeek>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof plannerControllerGetWeek>>,
          TError,
          Awaited<ReturnType<typeof plannerControllerGetWeek>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePlannerControllerGetWeek<
  TData = Awaited<ReturnType<typeof plannerControllerGetWeek>>,
  TError = unknown,
>(
  weekKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof plannerControllerGetWeek>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Piano settimana — tutti gli slot
 */

export function usePlannerControllerGetWeek<
  TData = Awaited<ReturnType<typeof plannerControllerGetWeek>>,
  TError = unknown,
>(
  weekKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof plannerControllerGetWeek>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPlannerControllerGetWeekQueryOptions(
    weekKey,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Assegna ricetta a uno slot
 */
export const plannerControllerAssign = (
  weekKey: string,
  dayIndex: number,
  meal: string,
  course: string,
  assignRecipeDto: AssignRecipeDto,
) => {
  return customInstance<PlanSlotResponseDto>({
    url: `/planner/${weekKey}/${dayIndex}/${meal}/${course}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: assignRecipeDto,
  });
};

export const getPlannerControllerAssignMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof plannerControllerAssign>>,
    TError,
    {
      weekKey: string;
      dayIndex: number;
      meal: string;
      course: string;
      data: AssignRecipeDto;
    },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof plannerControllerAssign>>,
  TError,
  {
    weekKey: string;
    dayIndex: number;
    meal: string;
    course: string;
    data: AssignRecipeDto;
  },
  TContext
> => {
  const mutationKey = ["plannerControllerAssign"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof plannerControllerAssign>>,
    {
      weekKey: string;
      dayIndex: number;
      meal: string;
      course: string;
      data: AssignRecipeDto;
    }
  > = (props) => {
    const { weekKey, dayIndex, meal, course, data } = props ?? {};

    return plannerControllerAssign(weekKey, dayIndex, meal, course, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlannerControllerAssignMutationResult = NonNullable<
  Awaited<ReturnType<typeof plannerControllerAssign>>
>;
export type PlannerControllerAssignMutationBody = AssignRecipeDto;
export type PlannerControllerAssignMutationError = unknown;

/**
 * @summary Assegna ricetta a uno slot
 */
export const usePlannerControllerAssign = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof plannerControllerAssign>>,
      TError,
      {
        weekKey: string;
        dayIndex: number;
        meal: string;
        course: string;
        data: AssignRecipeDto;
      },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof plannerControllerAssign>>,
  TError,
  {
    weekKey: string;
    dayIndex: number;
    meal: string;
    course: string;
    data: AssignRecipeDto;
  },
  TContext
> => {
  const mutationOptions = getPlannerControllerAssignMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Rimuovi ricetta da uno slot
 */
export const plannerControllerRemove = (
  weekKey: string,
  dayIndex: number,
  meal: string,
  course: string,
) => {
  return customInstance<PlanSlotResponseDto>({
    url: `/planner/${weekKey}/${dayIndex}/${meal}/${course}`,
    method: "DELETE",
  });
};

export const getPlannerControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof plannerControllerRemove>>,
    TError,
    { weekKey: string; dayIndex: number; meal: string; course: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof plannerControllerRemove>>,
  TError,
  { weekKey: string; dayIndex: number; meal: string; course: string },
  TContext
> => {
  const mutationKey = ["plannerControllerRemove"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof plannerControllerRemove>>,
    { weekKey: string; dayIndex: number; meal: string; course: string }
  > = (props) => {
    const { weekKey, dayIndex, meal, course } = props ?? {};

    return plannerControllerRemove(weekKey, dayIndex, meal, course);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlannerControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof plannerControllerRemove>>
>;

export type PlannerControllerRemoveMutationError = unknown;

/**
 * @summary Rimuovi ricetta da uno slot
 */
export const usePlannerControllerRemove = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof plannerControllerRemove>>,
      TError,
      { weekKey: string; dayIndex: number; meal: string; course: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof plannerControllerRemove>>,
  TError,
  { weekKey: string; dayIndex: number; meal: string; course: string },
  TContext
> => {
  const mutationOptions = getPlannerControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
