/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pina API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BulkCheckDto,
  ShoppingResponseDto,
  ToggleFavCartDto,
  ToggleFavCheckedDto,
  ToggleItemDto,
} from "../../model";

import { customInstance } from "../../axios-instance";

/**
 * @summary Lista spesa della settimana
 */
export const shoppingControllerGet = (
  weekKey: string,
  signal?: AbortSignal,
) => {
  return customInstance<ShoppingResponseDto>({
    url: `/shopping/${weekKey}`,
    method: "GET",
    signal,
  });
};

export const getShoppingControllerGetQueryKey = (weekKey?: string) => {
  return [`/shopping/${weekKey}`] as const;
};

export const getShoppingControllerGetQueryOptions = <
  TData = Awaited<ReturnType<typeof shoppingControllerGet>>,
  TError = unknown,
>(
  weekKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shoppingControllerGet>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getShoppingControllerGetQueryKey(weekKey);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof shoppingControllerGet>>
  > = ({ signal }) => shoppingControllerGet(weekKey, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!weekKey,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof shoppingControllerGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ShoppingControllerGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof shoppingControllerGet>>
>;
export type ShoppingControllerGetQueryError = unknown;

export function useShoppingControllerGet<
  TData = Awaited<ReturnType<typeof shoppingControllerGet>>,
  TError = unknown,
>(
  weekKey: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shoppingControllerGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof shoppingControllerGet>>,
          TError,
          Awaited<ReturnType<typeof shoppingControllerGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShoppingControllerGet<
  TData = Awaited<ReturnType<typeof shoppingControllerGet>>,
  TError = unknown,
>(
  weekKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shoppingControllerGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof shoppingControllerGet>>,
          TError,
          Awaited<ReturnType<typeof shoppingControllerGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShoppingControllerGet<
  TData = Awaited<ReturnType<typeof shoppingControllerGet>>,
  TError = unknown,
>(
  weekKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shoppingControllerGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Lista spesa della settimana
 */

export function useShoppingControllerGet<
  TData = Awaited<ReturnType<typeof shoppingControllerGet>>,
  TError = unknown,
>(
  weekKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shoppingControllerGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getShoppingControllerGetQueryOptions(weekKey, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Genera lista spesa dal piano settimanale
 */
export const shoppingControllerGenerate = (
  weekKey: string,
  signal?: AbortSignal,
) => {
  return customInstance<ShoppingResponseDto>({
    url: `/shopping/${weekKey}/generate`,
    method: "POST",
    signal,
  });
};

export const getShoppingControllerGenerateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof shoppingControllerGenerate>>,
    TError,
    { weekKey: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof shoppingControllerGenerate>>,
  TError,
  { weekKey: string },
  TContext
> => {
  const mutationKey = ["shoppingControllerGenerate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof shoppingControllerGenerate>>,
    { weekKey: string }
  > = (props) => {
    const { weekKey } = props ?? {};

    return shoppingControllerGenerate(weekKey);
  };

  return { mutationFn, ...mutationOptions };
};

export type ShoppingControllerGenerateMutationResult = NonNullable<
  Awaited<ReturnType<typeof shoppingControllerGenerate>>
>;

export type ShoppingControllerGenerateMutationError = unknown;

/**
 * @summary Genera lista spesa dal piano settimanale
 */
export const useShoppingControllerGenerate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof shoppingControllerGenerate>>,
      TError,
      { weekKey: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof shoppingControllerGenerate>>,
  TError,
  { weekKey: string },
  TContext
> => {
  const mutationOptions = getShoppingControllerGenerateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Spunta/deseleziona un articolo
 */
export const shoppingControllerToggleItem = (
  weekKey: string,
  toggleItemDto: ToggleItemDto,
) => {
  return customInstance<ShoppingResponseDto>({
    url: `/shopping/${weekKey}/toggle-item`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: toggleItemDto,
  });
};

export const getShoppingControllerToggleItemMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof shoppingControllerToggleItem>>,
    TError,
    { weekKey: string; data: ToggleItemDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof shoppingControllerToggleItem>>,
  TError,
  { weekKey: string; data: ToggleItemDto },
  TContext
> => {
  const mutationKey = ["shoppingControllerToggleItem"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof shoppingControllerToggleItem>>,
    { weekKey: string; data: ToggleItemDto }
  > = (props) => {
    const { weekKey, data } = props ?? {};

    return shoppingControllerToggleItem(weekKey, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ShoppingControllerToggleItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof shoppingControllerToggleItem>>
>;
export type ShoppingControllerToggleItemMutationBody = ToggleItemDto;
export type ShoppingControllerToggleItemMutationError = unknown;

/**
 * @summary Spunta/deseleziona un articolo
 */
export const useShoppingControllerToggleItem = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof shoppingControllerToggleItem>>,
      TError,
      { weekKey: string; data: ToggleItemDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof shoppingControllerToggleItem>>,
  TError,
  { weekKey: string; data: ToggleItemDto },
  TContext
> => {
  const mutationOptions =
    getShoppingControllerToggleItemMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Reset: deseleziona tutti gli articoli
 */
export const shoppingControllerReset = (
  weekKey: string,
  signal?: AbortSignal,
) => {
  return customInstance<ShoppingResponseDto>({
    url: `/shopping/${weekKey}/reset`,
    method: "POST",
    signal,
  });
};

export const getShoppingControllerResetMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof shoppingControllerReset>>,
    TError,
    { weekKey: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof shoppingControllerReset>>,
  TError,
  { weekKey: string },
  TContext
> => {
  const mutationKey = ["shoppingControllerReset"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof shoppingControllerReset>>,
    { weekKey: string }
  > = (props) => {
    const { weekKey } = props ?? {};

    return shoppingControllerReset(weekKey);
  };

  return { mutationFn, ...mutationOptions };
};

export type ShoppingControllerResetMutationResult = NonNullable<
  Awaited<ReturnType<typeof shoppingControllerReset>>
>;

export type ShoppingControllerResetMutationError = unknown;

/**
 * @summary Reset: deseleziona tutti gli articoli
 */
export const useShoppingControllerReset = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof shoppingControllerReset>>,
      TError,
      { weekKey: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof shoppingControllerReset>>,
  TError,
  { weekKey: string },
  TContext
> => {
  const mutationOptions = getShoppingControllerResetMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Segna come acquistati (da scontrino)
 */
export const shoppingControllerBulkCheck = (
  weekKey: string,
  bulkCheckDto: BulkCheckDto,
  signal?: AbortSignal,
) => {
  return customInstance<ShoppingResponseDto>({
    url: `/shopping/${weekKey}/bulk-check`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: bulkCheckDto,
    signal,
  });
};

export const getShoppingControllerBulkCheckMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof shoppingControllerBulkCheck>>,
    TError,
    { weekKey: string; data: BulkCheckDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof shoppingControllerBulkCheck>>,
  TError,
  { weekKey: string; data: BulkCheckDto },
  TContext
> => {
  const mutationKey = ["shoppingControllerBulkCheck"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof shoppingControllerBulkCheck>>,
    { weekKey: string; data: BulkCheckDto }
  > = (props) => {
    const { weekKey, data } = props ?? {};

    return shoppingControllerBulkCheck(weekKey, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ShoppingControllerBulkCheckMutationResult = NonNullable<
  Awaited<ReturnType<typeof shoppingControllerBulkCheck>>
>;
export type ShoppingControllerBulkCheckMutationBody = BulkCheckDto;
export type ShoppingControllerBulkCheckMutationError = unknown;

/**
 * @summary Segna come acquistati (da scontrino)
 */
export const useShoppingControllerBulkCheck = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof shoppingControllerBulkCheck>>,
      TError,
      { weekKey: string; data: BulkCheckDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof shoppingControllerBulkCheck>>,
  TError,
  { weekKey: string; data: BulkCheckDto },
  TContext
> => {
  const mutationOptions =
    getShoppingControllerBulkCheckMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Aggiungi/rimuovi preferito dal carrello settimanale
 */
export const shoppingControllerToggleFavCart = (
  weekKey: string,
  toggleFavCartDto: ToggleFavCartDto,
) => {
  return customInstance<ShoppingResponseDto>({
    url: `/shopping/${weekKey}/toggle-fav-cart`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: toggleFavCartDto,
  });
};

export const getShoppingControllerToggleFavCartMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof shoppingControllerToggleFavCart>>,
    TError,
    { weekKey: string; data: ToggleFavCartDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof shoppingControllerToggleFavCart>>,
  TError,
  { weekKey: string; data: ToggleFavCartDto },
  TContext
> => {
  const mutationKey = ["shoppingControllerToggleFavCart"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof shoppingControllerToggleFavCart>>,
    { weekKey: string; data: ToggleFavCartDto }
  > = (props) => {
    const { weekKey, data } = props ?? {};

    return shoppingControllerToggleFavCart(weekKey, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ShoppingControllerToggleFavCartMutationResult = NonNullable<
  Awaited<ReturnType<typeof shoppingControllerToggleFavCart>>
>;
export type ShoppingControllerToggleFavCartMutationBody = ToggleFavCartDto;
export type ShoppingControllerToggleFavCartMutationError = unknown;

/**
 * @summary Aggiungi/rimuovi preferito dal carrello settimanale
 */
export const useShoppingControllerToggleFavCart = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof shoppingControllerToggleFavCart>>,
      TError,
      { weekKey: string; data: ToggleFavCartDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof shoppingControllerToggleFavCart>>,
  TError,
  { weekKey: string; data: ToggleFavCartDto },
  TContext
> => {
  const mutationOptions =
    getShoppingControllerToggleFavCartMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Spunta un preferito come acquistato
 */
export const shoppingControllerToggleFavChecked = (
  weekKey: string,
  toggleFavCheckedDto: ToggleFavCheckedDto,
) => {
  return customInstance<ShoppingResponseDto>({
    url: `/shopping/${weekKey}/toggle-fav-checked`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: toggleFavCheckedDto,
  });
};

export const getShoppingControllerToggleFavCheckedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof shoppingControllerToggleFavChecked>>,
    TError,
    { weekKey: string; data: ToggleFavCheckedDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof shoppingControllerToggleFavChecked>>,
  TError,
  { weekKey: string; data: ToggleFavCheckedDto },
  TContext
> => {
  const mutationKey = ["shoppingControllerToggleFavChecked"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof shoppingControllerToggleFavChecked>>,
    { weekKey: string; data: ToggleFavCheckedDto }
  > = (props) => {
    const { weekKey, data } = props ?? {};

    return shoppingControllerToggleFavChecked(weekKey, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ShoppingControllerToggleFavCheckedMutationResult = NonNullable<
  Awaited<ReturnType<typeof shoppingControllerToggleFavChecked>>
>;
export type ShoppingControllerToggleFavCheckedMutationBody =
  ToggleFavCheckedDto;
export type ShoppingControllerToggleFavCheckedMutationError = unknown;

/**
 * @summary Spunta un preferito come acquistato
 */
export const useShoppingControllerToggleFavChecked = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof shoppingControllerToggleFavChecked>>,
      TError,
      { weekKey: string; data: ToggleFavCheckedDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof shoppingControllerToggleFavChecked>>,
  TError,
  { weekKey: string; data: ToggleFavCheckedDto },
  TContext
> => {
  const mutationOptions =
    getShoppingControllerToggleFavCheckedMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
