/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pina API
 * OpenAPI spec version: 1.0
 */
import type { IngredientDto } from "./ingredientDto";

export interface CreateRecipeDto {
  name: string;
  description?: string;
  tags: string[];
  servings: number;
  timeMinutes: number;
  rating?: number;
  ingredients: IngredientDto[];
  steps: string[];
}
