/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pina API
 * OpenAPI spec version: 1.0
 */

export interface FavoriteResponseDto {
  familyId: string;
  favId: string;
  name: string;
  category: string;
  defaultQty?: string;
  createdAt?: string;
}
