/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pina API
 * OpenAPI spec version: 1.0
 */
import type { ImportedIngredientDto } from "./importedIngredientDto";

export interface ImportedRecipeDto {
  name: string;
  description?: string;
  tags: string[];
  servings: number;
  timeMinutes: number;
  ingredients: ImportedIngredientDto[];
  steps: string[];
}
