/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pina API
 * OpenAPI spec version: 1.0
 */

export interface PantryItemResponseDto {
  familyId: string;
  itemId: string;
  name: string;
  category: string;
  inStock: boolean;
  updatedAt?: string;
}
