/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pina API
 * OpenAPI spec version: 1.0
 */
import type { RecipeRefDto } from "./recipeRefDto";

export interface PlanSlotResponseDto {
  familyId: string;
  slotKey: string;
  primo?: RecipeRefDto;
  secondo?: RecipeRefDto;
  updatedAt?: string;
}
