/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pina API
 * OpenAPI spec version: 1.0
 */
import type { ShoppingItemDto } from "./shoppingItemDto";
import type { FavCartEntryDto } from "./favCartEntryDto";

export interface ShoppingResponseDto {
  familyId: string;
  weekKey: string;
  items: ShoppingItemDto[];
  favCart: FavCartEntryDto[];
  generatedAt?: string;
  updatedAt?: string;
}
