/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pina API
 * OpenAPI spec version: 1.0
 */

export interface ShoppingItemDto {
  id: string;
  name: string;
  qty: string;
  count: number;
  category: string;
  checked: boolean;
}
