/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pina API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { CreateFavoriteDto, FavoriteResponseDto } from "../../model";

import { customInstance } from "../../axios-instance";

/**
 * @summary Lista articoli preferiti
 */
export const favoritesControllerGetAll = (signal?: AbortSignal) => {
  return customInstance<FavoriteResponseDto[]>({
    url: `/pina/favorites`,
    method: "GET",
    signal,
  });
};

export const getFavoritesControllerGetAllQueryKey = () => {
  return [`/pina/favorites`] as const;
};

export const getFavoritesControllerGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof favoritesControllerGetAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof favoritesControllerGetAll>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFavoritesControllerGetAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof favoritesControllerGetAll>>
  > = ({ signal }) => favoritesControllerGetAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof favoritesControllerGetAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FavoritesControllerGetAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof favoritesControllerGetAll>>
>;
export type FavoritesControllerGetAllQueryError = unknown;

export function useFavoritesControllerGetAll<
  TData = Awaited<ReturnType<typeof favoritesControllerGetAll>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof favoritesControllerGetAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof favoritesControllerGetAll>>,
          TError,
          Awaited<ReturnType<typeof favoritesControllerGetAll>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFavoritesControllerGetAll<
  TData = Awaited<ReturnType<typeof favoritesControllerGetAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof favoritesControllerGetAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof favoritesControllerGetAll>>,
          TError,
          Awaited<ReturnType<typeof favoritesControllerGetAll>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFavoritesControllerGetAll<
  TData = Awaited<ReturnType<typeof favoritesControllerGetAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof favoritesControllerGetAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Lista articoli preferiti
 */

export function useFavoritesControllerGetAll<
  TData = Awaited<ReturnType<typeof favoritesControllerGetAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof favoritesControllerGetAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFavoritesControllerGetAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Aggiungi articolo preferito
 */
export const favoritesControllerCreate = (
  createFavoriteDto: CreateFavoriteDto,
  signal?: AbortSignal,
) => {
  return customInstance<FavoriteResponseDto>({
    url: `/pina/favorites`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createFavoriteDto,
    signal,
  });
};

export const getFavoritesControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof favoritesControllerCreate>>,
    TError,
    { data: CreateFavoriteDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof favoritesControllerCreate>>,
  TError,
  { data: CreateFavoriteDto },
  TContext
> => {
  const mutationKey = ["favoritesControllerCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof favoritesControllerCreate>>,
    { data: CreateFavoriteDto }
  > = (props) => {
    const { data } = props ?? {};

    return favoritesControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type FavoritesControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof favoritesControllerCreate>>
>;
export type FavoritesControllerCreateMutationBody = CreateFavoriteDto;
export type FavoritesControllerCreateMutationError = unknown;

/**
 * @summary Aggiungi articolo preferito
 */
export const useFavoritesControllerCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof favoritesControllerCreate>>,
      TError,
      { data: CreateFavoriteDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof favoritesControllerCreate>>,
  TError,
  { data: CreateFavoriteDto },
  TContext
> => {
  const mutationOptions = getFavoritesControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Rimuovi articolo preferito
 */
export const favoritesControllerRemove = (favId: string) => {
  return customInstance<void>({
    url: `/pina/favorites/${favId}`,
    method: "DELETE",
  });
};

export const getFavoritesControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof favoritesControllerRemove>>,
    TError,
    { favId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof favoritesControllerRemove>>,
  TError,
  { favId: string },
  TContext
> => {
  const mutationKey = ["favoritesControllerRemove"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof favoritesControllerRemove>>,
    { favId: string }
  > = (props) => {
    const { favId } = props ?? {};

    return favoritesControllerRemove(favId);
  };

  return { mutationFn, ...mutationOptions };
};

export type FavoritesControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof favoritesControllerRemove>>
>;

export type FavoritesControllerRemoveMutationError = unknown;

/**
 * @summary Rimuovi articolo preferito
 */
export const useFavoritesControllerRemove = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof favoritesControllerRemove>>,
      TError,
      { favId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof favoritesControllerRemove>>,
  TError,
  { favId: string },
  TContext
> => {
  const mutationOptions = getFavoritesControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
