/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pina API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ProcessReceiptDto,
  ProcessReceiptResponseDto,
  UploadUrlResponseDto,
} from "../../model";

import { customInstance } from "../../axios-instance";

/**
 * @summary Get presigned S3 URL for receipt upload
 */
export const receiptControllerGetUploadUrl = (signal?: AbortSignal) => {
  return customInstance<UploadUrlResponseDto>({
    url: `/pina/receipt/upload-url`,
    method: "GET",
    signal,
  });
};

export const getReceiptControllerGetUploadUrlQueryKey = () => {
  return [`/pina/receipt/upload-url`] as const;
};

export const getReceiptControllerGetUploadUrlQueryOptions = <
  TData = Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getReceiptControllerGetUploadUrlQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>
  > = ({ signal }) => receiptControllerGetUploadUrl(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ReceiptControllerGetUploadUrlQueryResult = NonNullable<
  Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>
>;
export type ReceiptControllerGetUploadUrlQueryError = unknown;

export function useReceiptControllerGetUploadUrl<
  TData = Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>,
          TError,
          Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useReceiptControllerGetUploadUrl<
  TData = Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>,
          TError,
          Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useReceiptControllerGetUploadUrl<
  TData = Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get presigned S3 URL for receipt upload
 */

export function useReceiptControllerGetUploadUrl<
  TData = Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof receiptControllerGetUploadUrl>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getReceiptControllerGetUploadUrlQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Process uploaded receipt, update pantry and shopping list
 */
export const receiptControllerProcess = (
  processReceiptDto: ProcessReceiptDto,
  signal?: AbortSignal,
) => {
  return customInstance<ProcessReceiptResponseDto>({
    url: `/pina/receipt/process`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: processReceiptDto,
    signal,
  });
};

export const getReceiptControllerProcessMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof receiptControllerProcess>>,
    TError,
    { data: ProcessReceiptDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof receiptControllerProcess>>,
  TError,
  { data: ProcessReceiptDto },
  TContext
> => {
  const mutationKey = ["receiptControllerProcess"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof receiptControllerProcess>>,
    { data: ProcessReceiptDto }
  > = (props) => {
    const { data } = props ?? {};

    return receiptControllerProcess(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReceiptControllerProcessMutationResult = NonNullable<
  Awaited<ReturnType<typeof receiptControllerProcess>>
>;
export type ReceiptControllerProcessMutationBody = ProcessReceiptDto;
export type ReceiptControllerProcessMutationError = unknown;

/**
 * @summary Process uploaded receipt, update pantry and shopping list
 */
export const useReceiptControllerProcess = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof receiptControllerProcess>>,
      TError,
      { data: ProcessReceiptDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof receiptControllerProcess>>,
  TError,
  { data: ProcessReceiptDto },
  TContext
> => {
  const mutationOptions = getReceiptControllerProcessMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
